# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: swift
cache: cocoapods
podfile: Example/Podfile

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
- pod install --project-directory=Example

script:
- set -o pipefail
- xcodebuild -workspace "Example/MGKeyboardAccessory.xcworkspace" -scheme "MGKeyboardAccessory-Example" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
- xcodebuild -workspace "Example/MGKeyboardAccessory.xcworkspace" -scheme "MGKeyboardAccessory-Example" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
- pod lib lint --no-clean

after_success:
- sleep 5